### ISSUE TITLE
Resend Verification email loop

### ISSUE THREAD

**Issue by 0x3639** [LinkStackOrg/linkstack-docker#103]
I inserted new smtp credentials and tried to impersonate a user who was not receiving the email verification.  

I was presented with this message when I tried to impersonate the user.  I could not login as that user and when I clicked logout

<img width="554" alt="Screenshot 2023-11-18 at 3 58 10 PM" src="https://github.com/LinkStackOrg/linkstack-docker/assets/5406130/9a997b8f-290e-46b9-ba74-7a486f3d1add">

I was presented with this page.  Not sure why this is showing as insecure.  I'm using caddy and https was working correctly before I tried to impersonate someone with an account that was not email verified. 

<img width="727" alt="Screenshot 2023-11-18 at 3 58 16 PM" src="https://github.com/LinkStackOrg/linkstack-docker/assets/5406130/9ab8a282-6319-41f0-ba6f-6d379355a325">

I then try to manually insert https:// before the URL https://my.znn.link/logout  and get this error

https://flareapp.io/share/V7jW4qo5

Is there a way to log back in as admin given the state I'm in?

**Comment by lastsamurai26** [comment]
Do you using 443 between docker and caddy ?

**Comment by 0x3639** [comment]
Here is my docker compose file.  When using caddy and I reverse_proxy to http://localIP:8188 the site loads.  When I change the reverse_proxy to https://localIP:8190 I get a 502 error.  

```
version: "3.8"

services:

  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    environment:
      TZ: 'America/Chicago'
      SERVER_ADMIN: '0x3639@protonmail.com'
      HTTP_SERVER_NAME: 'my.znn.link'
      HTTPS_SERVER_NAME: 'my.znn.link'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - 'linkstack_data:/htdocs'
    ports:
      - '8188:80'
      - '8190:443'
    restart: unless-stopped

volumes:
  linkstack_data:
```
