### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by tilllt** [LinkStackOrg/linkstack-docker#54]
Using the docker-compose.yml based deployment with minimal manual changes to the example config from the README doesnt work, starting the docker leads to a an Error 500.

```
version: "3.8"

services:

  littlelink-custom:
    hostname: 'littlelink-custom'
    image: 'julianprieber/littlelink-custom:latest'
    environment:
      TZ: 'Europe/Berlin'
      SERVER_ADMIN: 'a@b.de'
      HTTP_SERVER_NAME: 'link.vrtlr.de'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - '/opt/docker/littlelink-custom/config/.env:/htdocs/.env:rw'
      - '/opt/docker/littlelink-custom/config/advanced-config.php:/htdocs/config/advanced-config.php:rw'
      - '/opt/docker/littlelink-custom/config/img:/htdocs/img:rw'
    ports:
      - '8388:80'
    restart: unless-stopped
```

I am running a haproxy ssl frontend, so i dont need port 443. the haproxy config is correct, i am running a dozen other docker based services with the same proxy. i assume its some sort of php misconfiguration, but since there is no error logging, regardless of the log_level i cannot say for sure.

Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Docker version 23.0.2, build 569dd73
Docker Compose version v2.17.2
