### ISSUE TITLE
empty htdocs after using docker-compose

### ISSUE THREAD

**Issue by C-Fu** [LinkStackOrg/linkstack-docker#66]
```
version: "3.8"

services:

  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    container_name: linkstack
    environment:
      TZ: 'Asia/Kuala_Lumpur'
      SERVER_ADMIN: 'email'
#      HTTP_SERVER_NAME: 'url'
      HTTPS_SERVER_NAME: 'url'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - './linkstack_data:/htdocs'
    ports:
      - '8188:80'
      - '8190:443'
    restart: unless-stopped
```

So if I run docker-compose.yml and look at the logs

```
Attaching to linkstack
linkstack    | cat: can't open '/htdocs/version.json': No such file or directory
linkstack    | + ------------------------------------------------------------------ +
linkstack    | |                      LINKSTACK v                           |
linkstack    | + ------------------------------------------------------------------ +
linkstack    | | Updating Configuration: Apache Base (/etc/apache2/httpd.conf)      |
linkstack    | | Updating Configuration: Apache SSL  (/etc/apache2/conf.d/ssl.conf) |
linkstack    | | Updating Configuration: PHP         (/etc/php81/php.ini)            |
linkstack    | | Updating Configuration: Complete                                   |
linkstack    | | ------------------------------------------------------------------ |
linkstack    | | Running Apache                                                     |
linkstack    | + ------------------------------------------------------------------ +
```

the linkstack_data/htdocs folder is empty. Not really sure why.

**Comment by lastsamurai26** [comment]
if you want to use a custom folder without the functionality of Docker you have to fill the mounted folder yourself

if you are using 
```
version: '3'
services:
  llc:
    container_name: llc
    image: linkstackorg/linkstack
    environment:
      - HTTP_SERVER_NAME="graf.hackeinbau.de" 
      - HTTPS_SERVER_NAME="graf.hackeinbau.de"
      - SERVER_ADMIN="admin@example.xyz"
      - TZ="Europe/Berlin"
      - PHP_MEMORY_LIMIT="512M"
      - UPLOAD_MAX_FILESIZE="8M"
    restart: always
    volumes:
      - linkstack_data:/htdocs
volumes:
  linkstack_data:

```
 it would be working :-)
