### ISSUE TITLE
dont work your image

### ISSUE THREAD

**Issue by AlFcl** [LinkStackOrg/linkstack-docker#80]
I have tried to download the Linkstack image, but it doesn't work at all. It always creates only the Apache server.

Index of /

Apache/2.4.56 (Unix) Server at alf.cl Port 8029

And the folder always comes empty. I tried with the alternative image, but it's the same.

`Version: '3.3'
services:
    linkstack:
        container_name: alfcl
        hostname: alfcl
        environment:
            - HTTP_SERVER_NAME=alf.cl
            - HTTPS_SERVER_NAME=alf.cl
            - SERVER_ADMIN=mail@alf.cl
            - TZ=America/Santiago
            - PHP_MEMORY_LIMIT=512M
            - UPLOAD_MAX_FILESIZE=8M
        ports:
            - '8029:80'
            - '8049:443'
        volumes:
            - ./htdoc:/htdocs

        restart: unless-stopped
        image: ghcr.io/linkstackorg/linkstack

volumes:
  linkstack:`

**Comment by lastsamurai26** [comment]
This is normal because you did not use a Docker volume but your own folder, so unfortunately you have to download the zip yourself and put it into the folder. 

if you using this one then it work 

```
version: "3.8"

services:

  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    environment:
      TZ: 'Europe/Berlin'
      SERVER_ADMIN: 'admin@example.com'
      HTTP_SERVER_NAME: 'sub00.de'
      HTTPS_SERVER_NAME: 'sub00.de'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    ports:
      - '8190:443'
      - '8090:80'
    volumes:
      - llc:/htdocs
    restart: unless-stopped
volumes:
  llc:
```
