### ISSUE TITLE
Cannot get WebSockets to work behind Nginx

### ISSUE THREAD

**Issue by bytebone** [LinkStackOrg/linkstack-docker#98]
### LinkStack version

latest on docker hub, unsure of version number

### Description

WebSockets refuse to work. I've done all I can to try and make it function, but it refuses service. I am using Nginx Proxy Manager as my reverse proxy, and i have multiple other containers that utilize websockets that work without problems. Usually I interact with NPM via the web dashboard, but to make sure all config is correct, I've looked into the generated nginx host file too, to make sure that all the [required headers and parameters](https://hub.docker.com/r/linkstackorg/linkstack#9) are present, **which they are**. I've checked the Chrome Dev Tools when on the website, and there is no WebSocket connection being made or even attempted when reloading or switching pages.

This also causes a very annoying flashbang on every page switch or data confirmation due to the fade-in animation by the way. I assume the body is not globally styled to be dark, so every time a new route is loaded I get a white window which then gets the content faded in. Not very nice to interact with.

### Details about your system

Ubuntu 20.04.5 LTS, but the image is running inside docker from a compose script. All PHP requirements are displayed as present by LinkStack

### How to reproduce

1. Install LinkStack via Compose
2. Enable "WebSocket Support" in the NPM host, or add the headers from the docs to the hostfile
3. No WebSocket

Let me know if you need more detailed steps, idk what to put here since this is not a niche bug. 

### compose file 
```yaml
version: "3.8"

services:

  linkstack:
    image: 'linkstackorg/linkstack:latest'
    container_name: linkstack
    environment:
      TZ: 'Europe/Berlin'
      SERVER_ADMIN: 'admin@website.dev'
      HTTP_SERVER_NAME: 'website.dev'
      HTTPS_SERVER_NAME: 'website.dev'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - data:/htdocs
    networks:
      - nginx_default
    #ports:
    #  - '8188:80'
    #  - '8190:443'
    restart: unless-stopped

volumes:
  data:

networks:
  nginx_default:
    external: true
```

### nginx hostfile
```
server {
  set $forward_scheme https;
  set $server         "linkstack";
  set $port           443;

  listen 80;
listen [::]:80;

listen 443 ssl http2;
listen [::]:443 ssl http2;

  server_name website.dev;

  # Custom SSL
  ssl_certificate /data/custom_ssl/npm-25/fullchain.pem;
  ssl_certificate_key /data/custom_ssl/npm-25/privkey.pem;

  # Block Exploits
  include conf.d/include/block-exploits.conf;

# Force SSL
    include conf.d/include/force-ssl.conf;

proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
proxy_http_version 1.1;

  access_log /data/logs/proxy-host-48_access.log proxy;
  error_log /data/logs/proxy-host-48_error.log warn;
 
location / {
    proxy_pass       https://linkstack:443;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

# headers from linkstack docs
    proxy_set_header X-VerifiedViaNginx yes;
    proxy_read_timeout 60;
    proxy_connect_timeout 60;
    proxy_redirect off;
    proxy_cache_bypass $http_upgrade;
   
    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```
_npm generates very ugly hostfiles, please excuse the bad formatting_
